#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers


domain=$(ynh_app_setting_get "$app" domain)


# Copy NGINX configuration
domain=$(ynh_app_setting_get "$app" domain)
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"

# Use gitlab-rake to backup
sudo gitlab-rake gitlab:backup:create

ynh_backup "/etc/gitlab/gitlab-secrets.json" "gitlab-secrets.json"
ynh_backup "/etc/gitlab/gitlab.rb" "gitlab.rb"
