#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path_url=$(ynh_app_setting_get "$app" path_url)


# Restore NGINX configuration
ynh_restore_file "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Restore gitlab configuration
ynh_restore_file "/etc/gitlab/gitlab.rb"
ynh_restore_file "/etc/gitlab/gitlab-secrets.json"


# Stop processes that are connected to the database
sudo service gitlab stop
sudo gitlab-ctl stop unicorn 
sudo gitlab-ctl stop sidekiq



sudo gitlab-rake gitlab:backup:restore BACKUP=1493107454_2017_04_25_9.1.0



sudo gitlab-ctl reconfigure

# Restart webserver
sudo service nginx reload


sudo gitlab-ctl start 
sudo gitlab-rake gitlab:check SANITIZE=true
